language: node_js
node_js:
  - 14
cache:
  yarn: true
  directories:
    - ~/.npm
    - ~/.cache
    - node_modules
stages:
  - Static Analysis
  - Tests
jobs:
  include:
    - stage: Static Analysis
      script: yarn lint:check
      name: lint:check
    - script: yarn type:check
      name: type:check
    - stage: Tests
      name: unit
      script: yarn test:unit
      install:
        - yarn global add codecov
      after_success:
        - codecov --disable gcov -f ./coverage/unit/lcov.info -F unit
    - name: integration
      script: yarn test:e2e
      install:
        - yarn global add codecov
        - yarn install --frozen-lockfile
        - yarn cypress install
        - yarn cypress verify
      after_success:
        - codecov --disable gcov -f ./coverage/integration/lcov.info -F integration
